#!/bin/sh

find_seeds() {
  find feeds -name '*.seed' -maxdepth 2
}

if [ $# -lt 1 ]; then
  if [ ! -z "$(command -v fzf)" ]; then
    SEED_FILE=$(find_seeds | fzf --height 25 --preview 'cat {}' --preview-window down:12)
  fi
else
  SEED_FILE=$1
fi
if [ ! -e "$SEED_FILE" ]; then
  cat <<EOF
Usage:
  $0 config_seed

Examples:
$(find feeds -name '*.seed' -maxdepth 2 | awk '{ print "  '"$0"' " $0; }')

EOF
  exit 2
fi

./scripts/feeds update -i &&
./scripts/feeds install -a &&
cp "$SEED_FILE" .config &&
make defconfig &&
make -j10 IGNORE_ERRORS="n m" BUILD_LOG=1 BUILD_LOG_DIR=bin/logs
